### PR TITLE
Adding LFX 2023 term 3

### PR DESCRIPTION
**Pull request by nate-double-u**
Adding: 
* LFX 2023 term 3
* LFX 2023 term 3 followup

### CODE REVIEW

**Comment by aliok** [comment]
@nate-double-u 

This won't work as is. I can make improvements to support this as well.

See https://github.com/aliok/mentorship-monitor/issues/46 for more information.

**Comment by aliok** [comment]
@nate-double-u 

I've done this. Please have a look at the UI: https://mentorship-monitor-ui.netlify.app/

I wrote some details here: https://github.com/aliok/mentorship-monitor/issues/46

But, in summary:
- There's now a new GH action: https://github.com/aliok/mentorship-monitor/actions/workflows/999-fetch-cohort-activity-summaries-manually.yaml
- This doesn't run periodically. You feed in the date range and the program name, and it will fetch it.
- I've written some docs here: https://github.com/aliok/mentorship-monitor?tab=readme-ov-file#100-fetch-cohort-activity-summariesjs

Once the this action is manually run with a date range until last week, the periodic task will pick it up in later executions.

**Comment by nate-double-u** [comment]
This is great @aliok, thanks so much!

I've got a couple more terms ready (data cleaned and setup in the spreadsheets). I'll open a couple more PRs for earlier terms and I can look at how to run the new actions to bring them in.

**Comment by aliok** [comment]
@nate-double-u 

It needs some manual work, but I am ok doing it. Send me the JSON over Slack and I can feed them to the system.

**Pull request closed without merging**
